---
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: Check that elastic user is connected
      uri:
        url: "http://localhost:9200/_stats"
        method: GET
        user: "elastic"
        password: "elastic"
