http.host: 0.0.0.0

cluster.name: "babidi"
node.name: "docker-image"

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

# xpack.graph.enabled: false
# xpack.ml.enabled: false
# xpack.monitoring.enabled: false
# xpack.security.enabled: true
# xpack.security.audit.enabled: true
# xpack.watcher.enabled: false

# anonymous user
# xpack.security.authc:
#   anonymous:
#     username: anonymous
#     roles: role_anonymous
#     authz_exception: true

action.destructive_requires_name: true

# http.cors.enabled: true
# http.cors.allow-origin: "*"

path.conf: /etc/elasticsearch
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

path.repo: ["/mnt/nfs"]

# cloud:
#   aws:
#     access_key: XXX
#     secret_key: XXX

# repositories:
#     s3:
#         bucket: "jin-es-backup-test"
#         region: "eu-west-1"
