http.host: 0.0.0.0

cluster.name: "babidi"
node.name: "docker-image"

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
